//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MenuExplorer.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MenuExplorer.Resources.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This demo shows how to apply a custom style to the C1Menu control..
        /// </summary>
        public static string CustomMenuAppearanceDesc {
            get {
                return ResourceManager.GetString("CustomMenuAppearanceDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom Appearance.
        /// </summary>
        public static string CustomMenuAppearanceTitle {
            get {
                return ResourceManager.GetString("CustomMenuAppearanceTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shows how to use C1RadialMenu with C1RichTextBox.
        /// </summary>
        public static string CustomRadialContextMenuDesc {
            get {
                return ResourceManager.GetString("CustomRadialContextMenuDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom Context Menu.
        /// </summary>
        public static string CustomRadialContextMenuTitle {
            get {
                return ResourceManager.GetString("CustomRadialContextMenuTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deep1.
        /// </summary>
        public static string Deep1 {
            get {
                return ResourceManager.GetString("Deep1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deep2.
        /// </summary>
        public static string Deep2 {
            get {
                return ResourceManager.GetString("Deep2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deep3.
        /// </summary>
        public static string Deep3 {
            get {
                return ResourceManager.GetString("Deep3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deep4.
        /// </summary>
        public static string Deep4 {
            get {
                return ResourceManager.GetString("Deep4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deep5.
        /// </summary>
        public static string Deep5 {
            get {
                return ResourceManager.GetString("Deep5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use the C1Menu control to create menu and C1ContextMenu control to attach pop-up menu to your interface. Nest menus to any depth, use an icon for each menu item along with the menu label, and even make menu items checkable..
        /// </summary>
        public static string DemoMenuDesc {
            get {
                return ResourceManager.GetString("DemoMenuDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Demo C1Menu.
        /// </summary>
        public static string DemoMenuTitle {
            get {
                return ResourceManager.GetString("DemoMenuTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shows how to use C1RadialMenu.
        /// </summary>
        public static string DemoRadialMenuDesc {
            get {
                return ResourceManager.GetString("DemoRadialMenuDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Demo C1RadialMenu.
        /// </summary>
        public static string DemoRadialMenuTitle {
            get {
                return ResourceManager.GetString("DemoRadialMenuTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document 1.
        /// </summary>
        public static string Document1 {
            get {
                return ResourceManager.GetString("Document1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document 2.
        /// </summary>
        public static string Document2 {
            get {
                return ResourceManager.GetString("Document2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document 3.
        /// </summary>
        public static string Document3 {
            get {
                return ResourceManager.GetString("Document3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document 4.
        /// </summary>
        public static string Document4 {
            get {
                return ResourceManager.GetString("Document4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create custom drop-downs using C1Menu. This demo shows how to create a dropdown menu using C1Menu inside a C1DropDownButton control..
        /// </summary>
        public static string DropDownMenuDesc {
            get {
                return ResourceManager.GetString("DropDownMenuDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drop Down Menu.
        /// </summary>
        public static string DropDownMenuTitle {
            get {
                return ResourceManager.GetString("DropDownMenuTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exclusive 1.
        /// </summary>
        public static string Exclusive1 {
            get {
                return ResourceManager.GetString("Exclusive1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exclusive 2.
        /// </summary>
        public static string Exclusive2 {
            get {
                return ResourceManager.GetString("Exclusive2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exclusive 3.
        /// </summary>
        public static string Exclusive3 {
            get {
                return ResourceManager.GetString("Exclusive3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shows how to display group labels between menu-items.
        /// </summary>
        public static string GroupingDesc {
            get {
                return ResourceManager.GetString("GroupingDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grouping.
        /// </summary>
        public static string GroupingTitle {
            get {
                return ResourceManager.GetString("GroupingTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string MenuItem_Close {
            get {
                return ResourceManager.GetString("MenuItem_Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deep.
        /// </summary>
        public static string MenuItem_Deep {
            get {
                return ResourceManager.GetString("MenuItem_Deep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string MenuItem_Edit {
            get {
                return ResourceManager.GetString("MenuItem_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        public static string MenuItem_Exit {
            get {
                return ResourceManager.GetString("MenuItem_Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File.
        /// </summary>
        public static string MenuItem_File {
            get {
                return ResourceManager.GetString("MenuItem_File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open.
        /// </summary>
        public static string MenuItem_Open {
            get {
                return ResourceManager.GetString("MenuItem_Open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page Setup.
        /// </summary>
        public static string MenuItem_PageSetup {
            get {
                return ResourceManager.GetString("MenuItem_PageSetup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print.
        /// </summary>
        public static string MenuItem_Print {
            get {
                return ResourceManager.GetString("MenuItem_Print", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Redo.
        /// </summary>
        public static string MenuItem_Redo {
            get {
                return ResourceManager.GetString("MenuItem_Redo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string MenuItem_Save {
            get {
                return ResourceManager.GetString("MenuItem_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save All.
        /// </summary>
        public static string MenuItem_SaveAll {
            get {
                return ResourceManager.GetString("MenuItem_SaveAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Undo.
        /// </summary>
        public static string MenuItem_Undo {
            get {
                return ResourceManager.GetString("MenuItem_Undo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Window.
        /// </summary>
        public static string MenuItem_Window {
            get {
                return ResourceManager.GetString("MenuItem_Window", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close Solution.
        /// </summary>
        public static string SubMenuItem_CloseSolution {
            get {
                return ResourceManager.GetString("SubMenuItem_CloseSolution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy.
        /// </summary>
        public static string SubMenuItem_Copy {
            get {
                return ResourceManager.GetString("SubMenuItem_Copy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cut.
        /// </summary>
        public static string SubMenuItem_Cut {
            get {
                return ResourceManager.GetString("SubMenuItem_Cut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string SubMenuItem_Delete {
            get {
                return ResourceManager.GetString("SubMenuItem_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File....
        /// </summary>
        public static string SubMenuItem_File {
            get {
                return ResourceManager.GetString("SubMenuItem_File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New.
        /// </summary>
        public static string SubMenuItem_New {
            get {
                return ResourceManager.GetString("SubMenuItem_New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paste.
        /// </summary>
        public static string SubMenuItem_Paste {
            get {
                return ResourceManager.GetString("SubMenuItem_Paste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project....
        /// </summary>
        public static string SubMenuItem_Project {
            get {
                return ResourceManager.GetString("SubMenuItem_Project", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Team Project....
        /// </summary>
        public static string SubMenuItem_TeamProject {
            get {
                return ResourceManager.GetString("SubMenuItem_TeamProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Web Site....
        /// </summary>
        public static string SubMenuItem_WebSite {
            get {
                return ResourceManager.GetString("SubMenuItem_WebSite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Theme.
        /// </summary>
        public static string Theme {
            get {
                return ResourceManager.GetString("Theme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MenuExplorer.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
    }
}
