//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DiagramExplorer.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DiagramExplorer.Resources.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Animal classification bound to flat data collection..
        /// </summary>
        public static string AnimalsDescription {
            get {
                return ResourceManager.GetString("AnimalsDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 🦁 Animals.
        /// </summary>
        public static string AnimalsTitle {
            get {
                return ResourceManager.GetString("AnimalsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dynamic graph representing current time..
        /// </summary>
        public static string ClockDescription {
            get {
                return ResourceManager.GetString("ClockDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 🕐 Diagram Clock.
        /// </summary>
        public static string ClockTitle {
            get {
                return ResourceManager.GetString("ClockTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FlexDiagram with collapsible nodes. Click on the node to collapse or expand..
        /// </summary>
        public static string CollapsibleDescription {
            get {
                return ResourceManager.GetString("CollapsibleDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ➕ Collapsible.
        /// </summary>
        public static string CollapsibleTitle {
            get {
                return ResourceManager.GetString("CollapsibleTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FlexDiagram with custom shape node..
        /// </summary>
        public static string CustomShapeDescription {
            get {
                return ResourceManager.GetString("CustomShapeDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 💧 Custom Shape.
        /// </summary>
        public static string CustomShapeTitle {
            get {
                return ResourceManager.GetString("CustomShapeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dark.
        /// </summary>
        public static string Dark {
            get {
                return ResourceManager.GetString("Dark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 📁 Data Binding.
        /// </summary>
        public static string DataBinding {
            get {
                return ResourceManager.GetString("DataBinding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shows sample decision tree diagram. The diagram is loaded from Mermaid.js graph..
        /// </summary>
        public static string DecisionTreeDescription {
            get {
                return ResourceManager.GetString("DecisionTreeDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 🌳 Decision Tree.
        /// </summary>
        public static string DecisionTreeTitle {
            get {
                return ResourceManager.GetString("DecisionTreeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default.
        /// </summary>
        public static string Default {
            get {
                return ResourceManager.GetString("Default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dynamic diagram generation with adaptive layout. Click on the diagram to pause / start generation..
        /// </summary>
        public static string DynamicDescription {
            get {
                return ResourceManager.GetString("DynamicDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ⏩ Dynamic Graph.
        /// </summary>
        public static string DynamicTitle {
            get {
                return ResourceManager.GetString("DynamicTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shows relations between main characters of Games of Thrones. The diagram is loaded from Mermaid.js graph..
        /// </summary>
        public static string FamilyTreeDescription {
            get {
                return ResourceManager.GetString("FamilyTreeDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 👪 Family Tree.
        /// </summary>
        public static string FamilyTreeTitle {
            get {
                return ResourceManager.GetString("FamilyTreeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shows diagram of FlexChart visualization components. The nodes include images which are generated by corresponding component..
        /// </summary>
        public static string FlexChartFamilyDescription {
            get {
                return ResourceManager.GetString("FlexChartFamilyDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 📈 FlexChart Family.
        /// </summary>
        public static string FlexChartFamilyTitle {
            get {
                return ResourceManager.GetString("FlexChartFamilyTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move mouse over nodes and edges to highlight. Click to recreate graph..
        /// </summary>
        public static string HitTestingDescription {
            get {
                return ResourceManager.GetString("HitTestingDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 🎯 HitTesting.
        /// </summary>
        public static string HitTestingTitle {
            get {
                return ResourceManager.GetString("HitTestingTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 🖱️ Interaction.
        /// </summary>
        public static string Interaction {
            get {
                return ResourceManager.GetString("Interaction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flowchart fully defined in XAML.
        /// </summary>
        public static string IntroDescription {
            get {
                return ResourceManager.GetString("IntroDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ➡️ Introduction.
        /// </summary>
        public static string IntroTitle {
            get {
                return ResourceManager.GetString("IntroTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Light.
        /// </summary>
        public static string Light {
            get {
                return ResourceManager.GetString("Light", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shows literature genre tree. The diagram is loaded from Mermaid.js graph..
        /// </summary>
        public static string LiteratureDescription {
            get {
                return ResourceManager.GetString("LiteratureDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 📚 Literature.
        /// </summary>
        public static string LiteratureTitle {
            get {
                return ResourceManager.GetString("LiteratureTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shows diagram with child nodes which include another diagrams..
        /// </summary>
        public static string NestedDescription {
            get {
                return ResourceManager.GetString("NestedDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 🗃 Nested Diagrams.
        /// </summary>
        public static string NestedTitle {
            get {
                return ResourceManager.GetString("NestedTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shows diagram with custom XAML template..
        /// </summary>
        public static string NodeTemplateDescription {
            get {
                return ResourceManager.GetString("NodeTemplateDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 📑 Node Template.
        /// </summary>
        public static string NodeTemplateTitle {
            get {
                return ResourceManager.GetString("NodeTemplateTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Organizational chart created with hierarchical data..
        /// </summary>
        public static string OrgChartDescription {
            get {
                return ResourceManager.GetString("OrgChartDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 👥 OrgChart.
        /// </summary>
        public static string OrgChartTitle {
            get {
                return ResourceManager.GetString("OrgChartTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Palette:.
        /// </summary>
        public static string Palette {
            get {
                return ResourceManager.GetString("Palette", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shows relationship and history of programming languages. The diagram is loaded from Mermaid.js graph..
        /// </summary>
        public static string ProgrammingLanguagesDescription {
            get {
                return ResourceManager.GetString("ProgrammingLanguagesDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 💻 Programming Languages.
        /// </summary>
        public static string ProgrammingLanguagesTitle {
            get {
                return ResourceManager.GetString("ProgrammingLanguagesTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FlexDiagram support node selection with customizable selection style. Click on the node to select..
        /// </summary>
        public static string SelectionDescription {
            get {
                return ResourceManager.GetString("SelectionDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ✔️ Selection.
        /// </summary>
        public static string SelectionTitle {
            get {
                return ResourceManager.GetString("SelectionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Theme.
        /// </summary>
        public static string Theme {
            get {
                return ResourceManager.GetString("Theme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can specify node and edge tooltips when creating FlexDiagram..
        /// </summary>
        public static string TooltipsDescription {
            get {
                return ResourceManager.GetString("TooltipsDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 💬 Tooltips.
        /// </summary>
        public static string TooltipsTitle {
            get {
                return ResourceManager.GetString("TooltipsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 📁 Unbound.
        /// </summary>
        public static string Unbound {
            get {
                return ResourceManager.GetString("Unbound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 📁 Usage Scenarios.
        /// </summary>
        public static string UsageScenarios {
            get {
                return ResourceManager.GetString("UsageScenarios", resourceCulture);
            }
        }
    }
}
