<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows10.0.19041.0</TargetFramework>
    <TargetPlatformMinVersion>10.0.17763.0</TargetPlatformMinVersion>
    <RootNamespace>DiagramExplorer</RootNamespace>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <Platforms>x86;x64;ARM64</Platforms>
    <RuntimeIdentifiers>win10-x86;win10-x64;win10-arm64</RuntimeIdentifiers>
    <PublishProfile>win10-$(Platform).pubxml</PublishProfile>
    <UseWinUI>true</UseWinUI>
    <EnableMsixTooling>true</EnableMsixTooling>
    <UseRidGraph>true</UseRidGraph>
    <ApplicationIcon>C1-ball.ico</ApplicationIcon>
  </PropertyGroup>
  <ItemGroup>
    <None Remove=".sa3licx" />
    <None Remove="Resources\African_Elephant.png" />
    <None Remove="Resources\Amanda_Rodriguez.png" />
    <None Remove="Resources\Andrew_Miller.png" />
    <None Remove="Resources\animals10.csv" />
    <None Remove="Resources\animals50.csv" />
    <None Remove="Resources\backend.mermaid" />
    <None Remove="Resources\Bald_Eagle.png" />
    <None Remove="Resources\Blue_Whale.png" />
    <None Remove="Resources\Brian_Clark.png" />
    <None Remove="Resources\Chris_Anderson.png" />
    <None Remove="Resources\countries.csv" />
    <None Remove="Resources\data.mermaid" />
    <None Remove="Resources\David_Chen.png" />
    <None Remove="Resources\decision-tree.mermaid" />
    <None Remove="Resources\Domestic_Cat.png" />
    <None Remove="Resources\Domestic_Dog.png" />
    <None Remove="Resources\Emma_Wilson.png" />
    <None Remove="Resources\Eric_Baker.png" />
    <None Remove="Resources\family-tree.mermaid" />
    <None Remove="Resources\flags\AE.png" />
    <None Remove="Resources\flags\AR.png" />
    <None Remove="Resources\flags\AT.png" />
    <None Remove="Resources\flags\AU.png" />
    <None Remove="Resources\flags\BD.png" />
    <None Remove="Resources\flags\BE.png" />
    <None Remove="Resources\flags\BR.png" />
    <None Remove="Resources\flags\BW.png" />
    <None Remove="Resources\flags\CA.png" />
    <None Remove="Resources\flags\CD.png" />
    <None Remove="Resources\flags\CI.png" />
    <None Remove="Resources\flags\CL.png" />
    <None Remove="Resources\flags\CM.png" />
    <None Remove="Resources\flags\CN.png" />
    <None Remove="Resources\flags\CO.png" />
    <None Remove="Resources\flags\CU.png" />
    <None Remove="Resources\flags\CZ.png" />
    <None Remove="Resources\flags\DE.png" />
    <None Remove="Resources\flags\DK.png" />
    <None Remove="Resources\flags\DO.png" />
    <None Remove="Resources\flags\DZ.png" />
    <None Remove="Resources\flags\EC.png" />
    <None Remove="Resources\flags\EG.png" />
    <None Remove="Resources\flags\ES.png" />
    <None Remove="Resources\flags\ET.png" />
    <None Remove="Resources\flags\FJ.png" />
    <None Remove="Resources\flags\FM.png" />
    <None Remove="Resources\flags\FR.png" />
    <None Remove="Resources\flags\GB.png" />
    <None Remove="Resources\flags\GH.png" />
    <None Remove="Resources\flags\GR.png" />
    <None Remove="Resources\flags\GT.png" />
    <None Remove="Resources\flags\HU.png" />
    <None Remove="Resources\flags\ID.png" />
    <None Remove="Resources\flags\IL.png" />
    <None Remove="Resources\flags\IN.png" />
    <None Remove="Resources\flags\IT.png" />
    <None Remove="Resources\flags\JM.png" />
    <None Remove="Resources\flags\JP.png" />
    <None Remove="Resources\flags\KE.png" />
    <None Remove="Resources\flags\KR.png" />
    <None Remove="Resources\flags\KZ.png" />
    <None Remove="Resources\flags\MA.png" />
    <None Remove="Resources\flags\MN.png" />
    <None Remove="Resources\flags\MX.png" />
    <None Remove="Resources\flags\NA.png" />
    <None Remove="Resources\flags\NG.png" />
    <None Remove="Resources\flags\NL.png" />
    <None Remove="Resources\flags\NO.png" />
    <None Remove="Resources\flags\NZ.png" />
    <None Remove="Resources\flags\PA.png" />
    <None Remove="Resources\flags\PE.png" />
    <None Remove="Resources\flags\PG.png" />
    <None Remove="Resources\flags\PK.png" />
    <None Remove="Resources\flags\PL.png" />
    <None Remove="Resources\flags\PT.png" />
    <None Remove="Resources\flags\QA.png" />
    <None Remove="Resources\flags\RO.png" />
    <None Remove="Resources\flags\SA.png" />
    <None Remove="Resources\flags\SB.png" />
    <None Remove="Resources\flags\SE.png" />
    <None Remove="Resources\flags\SG.png" />
    <None Remove="Resources\flags\SN.png" />
    <None Remove="Resources\flags\TH.png" />
    <None Remove="Resources\flags\TN.png" />
    <None Remove="Resources\flags\TZ.png" />
    <None Remove="Resources\flags\UA.png" />
    <None Remove="Resources\flags\US.png" />
    <None Remove="Resources\flags\UY.png" />
    <None Remove="Resources\flags\UZ.png" />
    <None Remove="Resources\flags\VE.png" />
    <None Remove="Resources\flags\VN.png" />
    <None Remove="Resources\flags\WS.png" />
    <None Remove="Resources\flags\ZA.png" />
    <None Remove="Resources\Frank_Adams.png" />
    <None Remove="Resources\frontend.mermaid" />
    <None Remove="Resources\Hannah_Collins.png" />
    <None Remove="Resources\House_Mouse.png" />
    <None Remove="Resources\Human.png" />
    <None Remove="Resources\Jennifer_Williams.png" />
    <None Remove="Resources\John_Smith.png" />
    <None Remove="Resources\Karen_White.png" />
    <None Remove="Resources\Laura_Walker.png" />
    <None Remove="Resources\Linda_Campbell.png" />
    <None Remove="Resources\Lisa_Wang.png" />
    <None Remove="Resources\literature.mermaid" />
    <None Remove="Resources\Little_Brown_Bat.png" />
    <None Remove="Resources\Mark_Robinson.png" />
    <None Remove="Resources\Michael_Brown.png" />
    <None Remove="Resources\Nicole_Harris.png" />
    <None Remove="Resources\Paul_Martinez.png" />
    <None Remove="Resources\Platypus.png" />
    <None Remove="Resources\programming-language-tree.mermaid" />
    <None Remove="Resources\Rebecca_Young.png" />
    <None Remove="Resources\Red_Kangaroo.png" />
    <None Remove="Resources\Robert_Taylor.png" />
    <None Remove="Resources\Sarah_Mitchell.png" />
    <None Remove="Resources\Sophia_Lewis.png" />
    <None Remove="Resources\Thomas_Anderson.png" />
    <None Remove="View\Contour.xaml" />
  </ItemGroup>
  <ItemGroup>
    <Content Include="Resources\David_Chen.png" />
  </ItemGroup>
  <ItemGroup>
    <Content Include="Assets\SplashScreen.scale-200.png" />
    <Content Include="Assets\LockScreenLogo.scale-200.png" />
    <Content Include="Assets\Square150x150Logo.scale-200.png" />
    <Content Include="Assets\Square44x44Logo.scale-200.png" />
    <Content Include="Assets\Square44x44Logo.targetsize-24_altform-unplated.png" />
    <Content Include="Assets\StoreLogo.png" />
    <Content Include="Assets\Wide310x150Logo.scale-200.png" />
    <Content Include="C1-ball.ico" />
    <Content Include="Resources\flags\AE.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Content>
    <Content Include="Resources\flags\AR.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Content>
    <Content Include="Resources\flags\AT.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Content>
    <Content Include="Resources\flags\AU.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Content>
    <Content Include="Resources\flags\BD.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Content>
    <Content Include="Resources\flags\BE.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Content>
    <Content Include="Resources\flags\BR.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Content>
    <Content Include="Resources\flags\BW.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Content>
    <Content Include="Resources\flags\CA.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Content>
    <Content Include="Resources\flags\CD.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Content>
    <Content Include="Resources\flags\CI.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Content>
    <Content Include="Resources\flags\CL.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Content>
    <Content Include="Resources\flags\CM.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Content>
    <Content Include="Resources\flags\CN.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Content>
    <Content Include="Resources\flags\CO.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Content>
    <Content Include="Resources\flags\CU.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Content>
    <Content Include="Resources\flags\CZ.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Content>
    <Content Include="Resources\flags\DE.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Content>
    <Content Include="Resources\flags\DK.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Content>
    <Content Include="Resources\flags\DO.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Content>
    <Content Include="Resources\flags\DZ.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Content>
    <Content Include="Resources\flags\EC.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Content>
    <Content Include="Resources\flags\EG.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Content>
    <Content Include="Resources\flags\ES.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Content>
    <Content Include="Resources\flags\ET.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Content>
    <Content Include="Resources\flags\FJ.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Content>
    <Content Include="Resources\flags\FM.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Content>
    <Content Include="Resources\flags\FR.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Content>
    <Content Include="Resources\flags\GB.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Content>
    <Content Include="Resources\flags\GH.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Content>
    <Content Include="Resources\flags\GR.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Content>
    <Content Include="Resources\flags\GT.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Content>
    <Content Include="Resources\flags\HU.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Content>
    <Content Include="Resources\flags\ID.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Content>
    <Content Include="Resources\flags\IL.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Content>
    <Content Include="Resources\flags\IN.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Content>
    <Content Include="Resources\flags\IT.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Content>
    <Content Include="Resources\flags\JM.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Content>
    <Content Include="Resources\flags\JP.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Content>
    <Content Include="Resources\flags\KE.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Content>
    <Content Include="Resources\flags\KR.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Content>
    <Content Include="Resources\flags\KZ.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Content>
    <Content Include="Resources\flags\MA.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Content>
    <Content Include="Resources\flags\MN.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Content>
    <Content Include="Resources\flags\MX.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Content>
    <Content Include="Resources\flags\NA.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Content>
    <Content Include="Resources\flags\NG.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Content>
    <Content Include="Resources\flags\NL.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Content>
    <Content Include="Resources\flags\NO.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Content>
    <Content Include="Resources\flags\NZ.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Content>
    <Content Include="Resources\flags\PA.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Content>
    <Content Include="Resources\flags\PE.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Content>
    <Content Include="Resources\flags\PG.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Content>
    <Content Include="Resources\flags\PK.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Content>
    <Content Include="Resources\flags\PL.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Content>
    <Content Include="Resources\flags\PT.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Content>
    <Content Include="Resources\flags\QA.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Content>
    <Content Include="Resources\flags\RO.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Content>
    <Content Include="Resources\flags\SA.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Content>
    <Content Include="Resources\flags\SB.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Content>
    <Content Include="Resources\flags\SE.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Content>
    <Content Include="Resources\flags\SG.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Content>
    <Content Include="Resources\flags\SN.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Content>
    <Content Include="Resources\flags\TH.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Content>
    <Content Include="Resources\flags\TN.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Content>
    <Content Include="Resources\flags\TZ.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Content>
    <Content Include="Resources\flags\UA.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Content>
    <Content Include="Resources\flags\US.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Content>
    <Content Include="Resources\flags\UY.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Content>
    <Content Include="Resources\flags\UZ.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Content>
    <Content Include="Resources\flags\VE.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Content>
    <Content Include="Resources\flags\VN.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Content>
    <Content Include="Resources\flags\WS.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Content>
    <Content Include="Resources\flags\ZA.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Content>
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include=".sa3licx" />
    <EmbeddedResource Include="Resources\animals10.csv" />
    <EmbeddedResource Include="Resources\animals50.csv" />
    <EmbeddedResource Include="Resources\backend.mermaid" />
    <EmbeddedResource Include="Resources\countries.csv" />
    <EmbeddedResource Include="Resources\data.mermaid" />
    <EmbeddedResource Include="Resources\decision-tree.mermaid" />
    <EmbeddedResource Include="Resources\family-tree.mermaid" />
    <EmbeddedResource Include="Resources\frontend.mermaid" />
    <EmbeddedResource Include="Resources\literature.mermaid" />
    <EmbeddedResource Include="Resources\programming-language-tree.mermaid" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="C1.Chart.Drawing" Version="10.0.20261.*" />
    <PackageReference Include="C1.WinUI.Chart">
      <Version>1.7.20261.127</Version>
    </PackageReference>
    <PackageReference Include="C1.WinUI.Core">
      <Version>1.7.20261.127</Version>
    </PackageReference>
    <PackageReference Include="C1.WinUI.Diagram">
      <Version>1.7.20261.127</Version>
    </PackageReference>
    <PackageReference Include="C1.WinUI.Input">
      <Version>1.7.20261.127</Version>
    </PackageReference>
    <PackageReference Include="C1.WinUI.Rendering">
      <Version>1.7.20261.127</Version>
    </PackageReference>
    <PackageReference Include="Microsoft.WindowsAppSDK" Version="1.7.251014001" />
    <Manifest Include="$(ApplicationManifest)" />
  </ItemGroup>
  <!-- 
    Defining the "Msix" ProjectCapability here allows the Single-project MSIX Packaging
    Tools extension to be activated for this project even if the Windows App SDK Nuget
    package has not yet been restored.
  -->
  <ItemGroup Condition="'$(DisableMsixProjectCapabilityAddedByProject)'!='true' and '$(EnableMsixTooling)'=='true'">
    <ProjectCapability Include="Msix" />
  </ItemGroup>
  <ItemGroup>
    <Content Include="Resources\African_Elephant.png" />
    <Content Include="Resources\Amanda_Rodriguez.png" />
    <Content Include="Resources\Andrew_Miller.png" />
    <Content Include="Resources\Bald_Eagle.png" />
    <Content Include="Resources\Blue_Whale.png" />
    <Content Include="Resources\Brian_Clark.png" />
    <Content Include="Resources\Chris_Anderson.png" />
    <Content Include="Resources\Domestic_Cat.png" />
    <Content Include="Resources\Domestic_Dog.png" />
    <Content Include="Resources\Emma_Wilson.png" />
    <Content Include="Resources\Eric_Baker.png" />
    <Content Include="Resources\Frank_Adams.png" />
    <Content Include="Resources\Hannah_Collins.png" />
    <Content Include="Resources\House_Mouse.png" />
    <Content Include="Resources\Human.png" />
    <Content Include="Resources\Jennifer_Williams.png" />
    <Content Include="Resources\John_Smith.png" />
    <Content Include="Resources\Karen_White.png" />
    <Content Include="Resources\Laura_Walker.png" />
    <Content Include="Resources\Linda_Campbell.png" />
    <Content Include="Resources\Lisa_Wang.png" />
    <Content Include="Resources\Little_Brown_Bat.png" />
    <Content Include="Resources\Mark_Robinson.png" />
    <Content Include="Resources\Michael_Brown.png" />
    <Content Include="Resources\Nicole_Harris.png" />
    <Content Include="Resources\Paul_Martinez.png" />
    <Content Include="Resources\Platypus.png" />
    <Content Include="Resources\Rebecca_Young.png" />
    <Content Include="Resources\Red_Kangaroo.png" />
    <Content Include="Resources\Robert_Taylor.png" />
    <Content Include="Resources\Sarah_Mitchell.png" />
    <Content Include="Resources\Sophia_Lewis.png" />
    <Content Include="Resources\Thomas_Anderson.png" />
  </ItemGroup>
  <ItemGroup>
    <Page Update="Samples\Intro.xaml">
      <Generator>MSBuild:Compile</Generator>
    </Page>
    <Page Update="View\ProgrammingLanguages.xaml">
      <SubType>Designer</SubType>
    </Page>
    <Page Update="View\Literature.xaml">
      <SubType>Designer</SubType>
    </Page>
  </ItemGroup>
  <ItemGroup>
    <Compile Update="Resources\AppResources.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>AppResources.resx</DependentUpon>
    </Compile>
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Update="Resources\AppResources.resx">
      <Generator>PublicResXFileCodeGenerator</Generator>
      <LastGenOutput>AppResources.Designer.cs</LastGenOutput>
    </EmbeddedResource>
  </ItemGroup>
  <!-- 
    Defining the "HasPackageAndPublishMenuAddedByProject" property here allows the Solution 
    Explorer "Package and Publish" context menu entry to be enabled for this project even if 
    the Windows App SDK Nuget package has not yet been restored.
  -->
  <PropertyGroup Condition="'$(DisableHasPackageAndPublishMenuAddedByProject)'!='true' and '$(EnableMsixTooling)'=='true'">
    <HasPackageAndPublishMenu>true</HasPackageAndPublishMenu>
  </PropertyGroup>
</Project>