//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccordionExplorer.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AccordionExplorer.Resources.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calendar.
        /// </summary>
        internal static string Calendar {
            get {
                return ResourceManager.GetString("Calendar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact 1.
        /// </summary>
        internal static string Contact1 {
            get {
                return ResourceManager.GetString("Contact1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact 2.
        /// </summary>
        internal static string Contact2 {
            get {
                return ResourceManager.GetString("Contact2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact 3.
        /// </summary>
        internal static string Contact3 {
            get {
                return ResourceManager.GetString("Contact3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact 4.
        /// </summary>
        internal static string Contact4 {
            get {
                return ResourceManager.GetString("Contact4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact 5.
        /// </summary>
        internal static string Contact5 {
            get {
                return ResourceManager.GetString("Contact5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contacts.
        /// </summary>
        internal static string Contacts {
            get {
                return ResourceManager.GetString("Contacts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ExpandDirection.
        /// </summary>
        internal static string ExpandDirection {
            get {
                return ResourceManager.GetString("ExpandDirection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ExpandMode.
        /// </summary>
        internal static string ExpandMode {
            get {
                return ResourceManager.GetString("ExpandMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fill.
        /// </summary>
        internal static string Fill {
            get {
                return ResourceManager.GetString("Fill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mail.
        /// </summary>
        internal static string Mail {
            get {
                return ResourceManager.GetString("Mail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mail 1.
        /// </summary>
        internal static string Mail1 {
            get {
                return ResourceManager.GetString("Mail1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mail 2.
        /// </summary>
        internal static string Mail2 {
            get {
                return ResourceManager.GetString("Mail2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mail 3.
        /// </summary>
        internal static string Mail3 {
            get {
                return ResourceManager.GetString("Mail3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mail 4.
        /// </summary>
        internal static string Mail4 {
            get {
                return ResourceManager.GetString("Mail4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mail 5.
        /// </summary>
        internal static string Mail5 {
            get {
                return ResourceManager.GetString("Mail5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Note 1.
        /// </summary>
        internal static string Note1 {
            get {
                return ResourceManager.GetString("Note1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Note2.
        /// </summary>
        internal static string Note2 {
            get {
                return ResourceManager.GetString("Note2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Note3.
        /// </summary>
        internal static string Note3 {
            get {
                return ResourceManager.GetString("Note3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Note 4.
        /// </summary>
        internal static string Note4 {
            get {
                return ResourceManager.GetString("Note4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Note 5.
        /// </summary>
        internal static string Note5 {
            get {
                return ResourceManager.GetString("Note5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notes.
        /// </summary>
        internal static string Notes {
            get {
                return ResourceManager.GetString("Notes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Task 1.
        /// </summary>
        internal static string Task1 {
            get {
                return ResourceManager.GetString("Task1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Task 2.
        /// </summary>
        internal static string Task2 {
            get {
                return ResourceManager.GetString("Task2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Task 3.
        /// </summary>
        internal static string Task3 {
            get {
                return ResourceManager.GetString("Task3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Task 4.
        /// </summary>
        internal static string Task4 {
            get {
                return ResourceManager.GetString("Task4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Task 5.
        /// </summary>
        internal static string Task5 {
            get {
                return ResourceManager.GetString("Task5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tasks.
        /// </summary>
        internal static string Tasks {
            get {
                return ResourceManager.GetString("Tasks", resourceCulture);
            }
        }
    }
}
